name: Publish Extension

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v0.1.0, etc.
  workflow_dispatch:  # Allows manual triggering
    inputs:
      version:
        description: 'Version to publish (leave empty to use package.json version)'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run type checking
      run: npm run check-types
      
    - name: Run compilation
      run: npm run compile
      
    - name: Run tests
      uses: coactions/setup-xvfb@v1
      with:
        run: npm test
        working-directory: ./
      
    - name: Package extension
      run: npm run vsce:package
      
    - name: Get package version
      id: package-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
    - name: Publish to VS Code Marketplace
      run: npm run vsce:publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-v${{ steps.package-version.outputs.version }}
        path: '*.vsix'
        retention-days: 30
